name: Test approval issue

on: push

jobs:
  test_this:
    runs-on: ubuntu-latest
    steps:
      - name: "Run local issue"
        uses: brissynet/create-approval-issue@v1
        with:
          labels: |
            label1
            label2
            label3
