name: Test approval issue

on: push

jobs:
  test_this:
    runs-on: ubuntu-latest
    steps:
      - name: "Run local issue"
        uses: brissynet/create-approval-issue@main
        with:
          repository: brissynet/create-approval-issue
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Hello everyone
          body: |
            Indeed Hello
            Everyone
          labels: |
            label1
            label2
            label3
