name: Pipeline apply

on:
  issues:
    types: [closed]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pipeline Details
        id: pipeline_details
        run: |
          echo "::set-output name=environment::$(echo $context | jq -r '.[].name' | grep environment)"
          echo "::set-output name=pipeline::$(echo $context | jq -r '.[].name' | grep pipeline)"
        env:
          context: ${{ toJSON(github.event.issue.labels) }}

      - name: Call the end pipeline
        run: |
          echo "${{ steps.pipeline_details.outputs.environment }}"
          echo "${{ steps.pipeline_details.outputs.environment }}"
