name: Pipeline apply

on:
  issues:
    types: [closed]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $context | jq -r '.[].name'
      - env:
          context: ${{ toJSON(github.event.issue.labels) }}
